### ISSUE TITLE
Log warnings in ImageAsset.image and SystemImage.image when loadImage() fails

### ISSUE THREAD

**Issue by mpospese** [yml-org/YCoreUI#51]
Let's log to console from `var image: UIImage` when `loadImage()` returns `nil` and we resort to the fallback image.
(This is preferable to logging from `loadImage()` which can be expected to return `nil` under certain unit tests.)

See how YMatterType logs when fonts don't load and let's adopt a similar pattern for declaring the `Logger` to use.
This will be iOS 14+.

**Comment by WestonHanners** [comment]
Can you cite an example of the YMatterType logging you speak of?
